// Every requirement in stage-1.md, read out of the specification text itself.
//
// The numbering is shared with the room plan's inventory so the three seats can talk
// about the same reference, but the entries here were taken from the specification, and
// the suite's coverage is measured against THIS list. A reference with no check is
// reported as a gap by `node main.mjs --coverage`.
//
// D-entries are the coordinator's recorded interpretations of places where the
// specification is silent. They are checked, but only ever as advisory: a service that
// reads the text differently is not violating it.

export const REQUIREMENTS = [
  // ---- 1 Scope -------------------------------------------------------------
  ['R1.1', '1', 'Users can send money by handle.'],
  ['R1.2', '1', 'Users can request money.'],
  ['R1.3', '1', 'Users can split bills.'],
  ['R1.4', '1', 'Payments appear in an activity feed with public or private visibility.'],
  ['R1.5', '1', 'Authorized operators can submit groups of transfers as settlements.'],
  ['R1.6', '1', 'Only the HTTP API is required.'],
  ['R1.7', '1', 'The sum of wallet balances always equals the total seeded by the last POST /_test/reset, including under concurrent requests and retries.'],
  ['R1.8', '1', 'No wallet balance may be negative, including transiently.'],
  ['R1.9', '1', 'A payment request may move money at most once.'],
  ['R1.10', '1', 'All amounts are exact integer counts of minor units.'],
  ['R1.11', '1', 'Deposits, top-ups, withdrawals, cards and bank integrations are out of scope; money moves only between existing wallets.'],

  // ---- 2 Delivery and deployment -------------------------------------------
  ['R2.1', '2', 'An HTTP service, a Dockerfile and a RUN.md with a command that builds and starts the service without manual setup.'],
  ['R2.2', '2', 'A docker-compose.yml is optional.'],
  ['R2.3', '2', 'The submission is a containerized HTTP service, not a Python package; language, framework and storage are unrestricted.'],
  ['R2.4', '2', 'The image must run on its own with -e PORT=<port> and a port mapping.'],
  ['R2.5', '2', 'No outbound network at run time; all dependencies, initialization and seed data work inside the one container.'],
  ['R2.6', '2', 'Resource limits: 2 vCPU, 2 GiB, 60 s to first healthy response, up to 50 requests in flight, 5 s per request (10 s for POST /_test/reset), ephemeral disk.'],
  ['R2.7', '2', 'Runtime assets and dependencies are included in the image.'],

  // ---- 3 Runtime contract --------------------------------------------------
  ['R3.1', '3.1', 'Listen on 0.0.0.0 using the PORT environment variable, default 8080.'],
  ['R3.2', '3.2', 'GET /health returns 200 {"status":"ok"} once the service and its data store can serve requests, within 60 s of container start.'],
  ['R3.3', '3.3', 'POST /_test/reset replaces all state with the fixture and returns 204; afterwards only that fixture is visible; repeated resets are supported; it is enabled in the delivered image and needs no authentication.'],
  ['R3.4a', '3.4', 'Requests and responses are application/json; charset=utf-8.'],
  ['R3.4b', '3.4', 'Timestamps in responses are RFC 3339 with an explicit offset.'],
  ['R3.4c', '3.4', 'Unknown fields in a request body are ignored, never an error.'],
  ['R3.4d', '3.4', 'Unknown query parameters are ignored.'],
  ['R3.4e', '3.4', 'IDs are opaque strings of at most 64 characters.'],

  // ---- 4 Model -------------------------------------------------------------
  ['R4.1', '4', 'One currency, declared in the fixture; every API amount is an integer count of its minor units.'],
  ['R4.2', '4', 'API amounts must have an integral numeric value: 1000, 1000.0 and 1e3 are the same valid amount; booleans and strings are not numbers.'],
  ['R4.3', '4', 'Every user has a handle: unique across the service, matching ^[a-z0-9_]{1,20}$, never changing once set.'],
  ['R4.4', '4', 'Users identify recipients by handle; directory and user-search endpoints are out of scope.'],
  ['R4.5', '4', 'Seeded users take their handle from the fixture.'],
  ['R4.6', '4', 'A signed-up user has a handle derived from the email: local part, lowercased, every character outside [a-z0-9_] replaced with _, truncated to 20 characters.'],
  ['R4.7', '4', 'If the derived handle is already taken the signup fails.'],
  ['R4.8', '4', 'New users start with a balance of 0 and can receive money and be asked for money immediately.'],
  ['R4.9', '4', 'A payment moves money from one wallet to another immediately and atomically, sent directly or created by paying a request.'],
  ['R4.10', '4', 'A request is pending and then exactly one of paid, declined or cancelled; only the payer may pay or decline, only the requester may cancel.'],
  ['R4.11', '4', 'A request may exceed the payer balance; it stays pending, paying while short is 409 insufficient_funds and changes nothing, and money arriving later makes it payable.'],
  ['R4.12', '4', 'Visibility belongs to the payment, not the request; the payer chooses it when the money moves; a request carries no visibility and never appears in anyone else\'s feed.'],
  ['R4.13', '4', 'GET /activity returns payments only, visible if and only if the payment is public or the caller is its sender or receiver. No other rule.'],
  ['R4.14', '4', 'Requests never appear in the activity feed; GET /requests returns only requests where the caller is requester or payer.'],
  ['R4.15', '4', 'A split is not a feed item; its requests are visible to their own two parties and the payments that fulfil them follow the feed rule.'],
  ['R4.16', '4', 'Visibility is one value on the payment, seen identically by both parties and by everyone else; a private payment is hidden from third parties, not from its own receiver.'],
  ['R4.17', '4', 'amount is at most 1000000000 on any single request; no operation produces a balance outside 2^53; monetary arithmetic is exact.'],
  ['R4.18', '4', 'The fixture format: currency, minor_units, users[], payments[], requests[] with the fields shown.'],
  ['R4.19', '4', 'Seeded users can log in with the given password immediately.'],
  ['R4.20', '4', 'A seeded balance is the balance after every seeded payment; seeded payments are not replayed against balances.'],
  ['R4.21', '4', 'A balance below zero in a fixture is a reset error: 422 validation_failed, changing nothing.'],
  ['R4.22', '4', 'minor_units is 0, 2 or 3; fixtures use EUR (2), JPY (0) and BHD (3).'],
  ['R4.23', '4', 'An administrative balance endpoint is out of scope.'],

  // ---- 5 Errors ------------------------------------------------------------
  ['R5.1', '5', 'Every 4xx and 5xx response carries {"error":{"code":..,"message":..}}.'],
  ['R5.2', '5', '400 malformed_request: an unparseable body, or a field of the wrong JSON type.'],
  ['R5.3', '5', '400 missing_idempotency_key: a required Idempotency-Key header absent or empty.'],
  ['R5.4', '5', '401 unauthenticated: a missing, malformed or unknown bearer token.'],
  ['R5.5', '5', '403 forbidden: authenticated but not permitted to touch this resource.'],
  ['R5.6', '5', '404 not_found: no such resource, or not visible to this caller.'],
  ['R5.7', '5', '409 idempotency_key_reuse: a key already used by this caller with a different request body.'],
  ['R5.8', '5', '422 validation_failed: a required field or query parameter is missing, or a stated rule is violated with no more specific code.'],
  ['R5.9', '5', 'A field of the correct JSON type with an invalid format or out-of-range value gives 422 validation_failed unless the endpoint specifies otherwise.'],
  ['R5.10', '5', 'Endpoint field rules take precedence: an invalid amount (including strings and booleans), a non-string note (including null) and any visibility other than public or private are 422; omission alone selects the optional-field default.'],
  ['R5.11', '5', 'An integer-valued query parameter is plain decimal digits: 1e9, 4.0 and +4 are 422 whatever their numeric value.'],
  ['R5.12', '5', '400 malformed_request is reserved for a body that does not parse or a field of the wrong type.'],
  ['R5.13', '5', 'Idempotency-Key is 1 to 255 characters, otherwise 422 validation_failed.'],
  ['R5.14', '5', 'limit is an integer 1 to 200, otherwise 422 validation_failed.'],
  ['R5.15', '5', 'offset is an integer 0 or more, otherwise 422 validation_failed.'],
  ['R5.16', '5', 'Requests must not produce 5xx responses, including under concurrent load.'],

  // ---- 6 Authentication ----------------------------------------------------
  ['R6.1', '6', 'POST /auth/signup {email,password,display_name} returns 201 {user_id, display_name, token}.'],
  ['R6.2', '6', 'POST /auth/login {email,password} returns 200 {user_id, display_name, token}.'],
  ['R6.3', '6', 'An already registered email is 409 email_taken.'],
  ['R6.4', '6', 'A password shorter than 8 characters is 422 validation_failed.'],
  ['R6.5', '6', 'An email not of the form local@domain is 422 validation_failed.'],
  ['R6.6', '6', 'A wrong password or an unknown email on login is 401 unauthenticated.'],
  ['R6.7', '6', 'A derived handle already taken is 409 handle_taken, and no account is created.'],
  ['R6.8', '6', 'Every other endpoint requires a bearer token, except /health, /_test/reset and the two auth endpoints (and the section 10 test endpoints, which are stated unauthenticated).'],
  ['R6.9', '6', 'Authorization: Bearer <token>.'],
  ['R6.10', '6', 'Tokens do not expire; an account may have multiple valid tokens and concurrent sessions.'],
  ['R6.11', '6', 'Passwords are stored with bcrypt, scrypt, Argon2 or an equivalent; plaintext storage is not permitted.'],
  ['R6.12', '6', 'Email verification, password reset, refresh tokens and role-management endpoints are out of scope.'],

  // ---- 7 Idempotency -------------------------------------------------------
  ['R7.1', '7', 'Five write paths require an idempotency key: POST /payments, POST /requests, POST /requests/{id}/pay, POST /splits and POST /settlements, each independently.'],
  ['R7.2', '7', 'The key is a client-chosen string of 1 to 255 characters.'],
  ['R7.3', '7', 'The key is scoped to the authenticated user; two users may use the same string with no interaction.'],
  ['R7.4', '7', 'A replay is the same user, method, path and body; the same key and body on a different path is a different request and must succeed normally.'],
  ['R7.5', '7', 'Header absent or empty: 400 missing_idempotency_key.'],
  ['R7.6', '7', 'First use of the key: the normal response, 201.'],
  ['R7.7', '7', 'Replay with the same body: 200, with a body identical to the original response as a JSON value.'],
  ['R7.8', '7', 'The same key with a different body: 409 idempotency_key_reuse.'],
  ['R7.9', '7', 'A key reused after the original request failed with 4xx is treated as a first use.'],
  ['R7.10', '7', '"Same body" means the same JSON value after parsing; key order and whitespace do not matter.'],
  ['R7.11', '7', 'For concurrent identical requests with an unused key, exactly one returns 201 and the others 200 with the same body; the operation takes effect only once.'],
  ['R7.12', '7', 'A successful replay returns the original response even after the resource changes or is cancelled, and makes no further state changes.'],
  ['R7.13', '7', 'After the body has parsed as a JSON object and the caller is authenticated, an already claimed key is resolved before endpoint field validation or current-resource checks.'],

  // ---- 8 API ---------------------------------------------------------------
  ['R8.1', '8', 'GET /me returns {user_id, display_name, handle, balance, currency, minor_units}.'],
  ['R8.2', '8', 'POST /payments takes to_handle, amount, note (optional, default "") and visibility (optional, default "public").'],
  ['R8.3', '8', 'A payment is {payment_id, from_user_id, from_handle, to_user_id, to_handle, amount, currency, note, visibility, request_id, created_at}.'],
  ['R8.4', '8', 'A caller balance below amount is 409 insufficient_funds.'],
  ['R8.5', '8', 'An amount below 1, above 1000000000, or not an integer is 422 validation_failed.'],
  ['R8.6', '8', 'to_handle equal to the caller own handle is 422 self_payment.'],
  ['R8.7', '8', 'A note longer than 200 characters is 422 validation_failed.'],
  ['R8.8', '8', 'A visibility other than public or private is 422 validation_failed.'],
  ['R8.9', '8', 'No user with that handle is 404 not_found.'],
  ['R8.10', '8', 'The debit and the credit are one atomic step; a payment is never visible in one wallet and not the other, and a failed payment leaves no trace in either.'],
  ['R8.11', '8', 'A note is stored and returned verbatim: no trimming, escaping or normalisation; Unicode and emoji survive byte for byte.'],
  ['R8.12', '8', 'POST /requests takes payer_handle, amount and note; the caller is the requester.'],
  ['R8.13', '8', 'A request is {request_id, requester_id, requester_handle, payer_id, payer_handle, amount, currency, note, status, payment_id, created_at}.'],
  ['R8.14', '8', 'Request errors: amount out of range 422; payer_handle the caller own 422 self_request; note over 200 characters 422; unknown handle 404.'],
  ['R8.15', '8', 'The payer balance is not checked when a request is created.'],
  ['R8.16', '8', 'POST /requests/{id}/pay is the payer only; the body carries visibility only, optional, default public; a replay must send the identical body, so {} and {"visibility":"public"} are different.'],
  ['R8.17', '8', 'Pay returns 201 with the created payment exactly as POST /payments returns one, request_id set to this request; the request becomes paid and carries the new payment_id.'],
  ['R8.18', '8', 'Pay errors: not pending 409 request_not_pending; balance below amount 409 insufficient_funds; caller not the payer 403 forbidden; unknown request 404 not_found.'],
  ['R8.19', '8', 'Replaying a successful pay returns 200 with the original payment body even though the request is already paid, moves no money, and must not return 409 request_not_pending.'],
  ['R8.20', '8', 'POST /requests/{id}/decline is the payer only, takes no idempotency key, returns 200 declined; declining twice is 200; a paid or cancelled request is 409 request_not_pending; not the payer is 403.'],
  ['R8.21', '8', 'POST /requests/{id}/cancel is the requester only, takes no idempotency key, returns 200 cancelled; cancelling twice is 200; a paid or declined request is 409 request_not_pending; not the requester is 403.'],
  ['R8.22', '8', 'GET /requests returns requests where the caller is requester or payer and no others, newest first by created_at.'],
  ['R8.23', '8', 'direction is incoming (the caller is the payer), outgoing (the caller is the requester) or absent for both.'],
  ['R8.24', '8', 'status is one of the four statuses, or absent for all.'],
  ['R8.25', '8', 'limit defaults to 50, range 1 to 200; offset defaults to 0 and must be 0 or more; outside either range is 422, as is an unknown direction or status value.'],
  ['R8.26', '8', 'has_more is true when items exist beyond the last one returned.'],
  ['R8.27', '8', 'GET /requests returns {"requests":[..],"has_more":bool}.'],
  ['R8.28', '8', 'POST /splits takes amount, participant_handles and note; the caller may be included in participant_handles or omitted.'],
  ['R8.29', '8', 'Shares follow the section 9 rule in the order the handles are given; a request is created for every participant except the caller, each for that participant share, with the caller as requester.'],
  ['R8.30', '8', 'A split is {split_id, amount, currency, note, shares[{handle,amount}], requests[..], created_at}.'],
  ['R8.31', '8', 'shares covers every participant including the caller, in the order given, and always sums to amount; requests covers every participant except the caller, in the same order.'],
  ['R8.32', '8', 'Split errors: amount out of range 422; participant_handles empty or containing a duplicate 422; note over 200 characters 422; any unknown handle 404.'],
  ['R8.33', '8', 'A split whose only participant is the caller is valid: one share, zero requests, "requests": [].'],
  ['R8.34', '8', 'Nothing about a split checks anyone balance.'],
  ['R8.35', '8', 'GET /activity returns payments visible by the feed contract, newest first by created_at, as {"payments":[..],"has_more":bool}.'],
  ['R8.36', '8', 'The relative order of two payments created within the same second is unspecified, and stable pagination during concurrent writes is not required for GET /activity.'],
  ['R8.37', '8', 'limit and offset on GET /activity behave exactly as on GET /requests.'],
  ['R8.38', '8', 'An item in GET /activity is a payment object of the shape in R8.3.'],
  ['R8.39', '8', 'An item in GET /requests is a request object of the shape in R8.13.'],

  // ---- 9 Money and rounding ------------------------------------------------
  ['R9.1', '9', 'Shares are whole minor units, sum exactly to amount, and differ by at most one minor unit.'],
  ['R9.2', '9', 'When the amount does not divide evenly the larger shares go to the first participants in participant_handles order.'],
  ['R9.3', '9', 'The stated table: 1000/3 -> 334,333,333; 1/3 -> 1,0,0; 10/3 -> 4,3,3; 999/3 -> 333,333,333; 5/5 -> 1,1,1,1,1.'],
  ['R9.4', '9', 'A different participant order gives the extra unit to a different person; a share of 0 is legal and still produces a request.'],
  ['R9.5', '9', 'Each split shares are independent of previous splits; after any number of splits have been paid in full, balances still sum exactly to the seeded total.'],

  // ---- 10 Export and import ------------------------------------------------
  ['R10.1', '10', 'GET /_test/export and POST /_test/import exist and, like reset, are unauthenticated test endpoints.'],
  ['R10.2', '10', 'Export returns 200 with a JSON object containing track: "pocketful", format_version: 1 and state (an implementation-defined JSON object).'],
  ['R10.3', '10', 'The state format is opaque to the caller and must be accepted unchanged by import.'],
  ['R10.4', '10', 'Import takes that entire object and atomically replaces the service state, returning 204.'],
  ['R10.5', '10', 'Import must accept an unchanged export produced by this service.'],
  ['R10.6', '10', 'No dependency on the source process, files, volume, port or network address is allowed.'],
  ['R10.7', '10', 'Import is replacement, not merge; repeating it restores the exported state without duplicating anything.'],
  ['R10.8', '10', 'Invalid JSON follows section 5; missing fields, a wrong track or version, or an invalid state give 422 validation_failed without changing the destination.'],
  ['R10.9', '10', 'Test control calls have a 10-second timeout.'],
  ['R10.10', '10', 'Export is an atomic, read-only snapshot; subsequent source writes do not change it.'],
  ['R10.11', '10', 'Preserve accounts and hashed-password login, existing bearer tokens, currency, balances, payments, requests, permissions, and all completed idempotent request bodies and original responses.'],
  ['R10.12', '10', 'Identities, timestamps and monetary records must not be regenerated or replayed against an already-net balance.'],
  ['R10.13', '10', 'Failed request keys remain reusable.'],
  ['R10.14', '10', 'Existing receipts, tokens and retries remain valid after import; replacing the state with a fresh fixture does not satisfy this.'],
  ['R10.15', '10', 'Import removes all previous destination data and credentials.'],
  ['R10.16', '10', 'Reset clears all state, including imported state.'],
  ['R10.17', '10', 'State need not survive an abrupt container restart.'],
  ['R10.18', '10', 'Exports may contain credentials and session tokens; handle them as private test artifacts.'],

  // ---- 11 Atomic net settlements -------------------------------------------
  ['R11.1', '11', 'The reset fixture may include settlement_operator_ids, an array of user ids, default [].'],
  ['R11.2', '11', 'An operator may execute a settlement across any wallets; the permission does not grant access to another user requests or private activity items.'],
  ['R11.3', '11', 'POST /settlements requires an operator and an idempotency key; no token is 401, an authenticated non-operator is 403 forbidden.'],
  ['R11.4', '11', 'The body is {"transfers":[{from_handle,to_handle,amount}, ..]}.'],
  ['R11.5', '11', 'transfers contains 1 to 32 objects.'],
  ['R11.6', '11', 'Each entry uses the ordinary payment amount, note and visibility rules, defaulting to an empty note and public.'],
  ['R11.7', '11', 'An unknown handle is 404, a self-transfer is 422 self_payment, and a malformed batch shape is 422 validation_failed.'],
  ['R11.8', '11', 'Entry errors take precedence in input order, before insufficient funds.'],
  ['R11.9', '11', 'Unknown fields are ignored.'],
  ['R11.10', '11', 'A settlement is affordable when every wallet balance after all incoming and outgoing transfers is nonnegative; insufficient collective funds is 409 insufficient_funds.'],
  ['R11.11', '11', 'Either all movements commit together or none do; failed validation claims no idempotency key and creates no payment or revision.'],
  ['R11.12', '11', 'Return 201 with settlement_id, committed_at and payments in input order.'],
  ['R11.13', '11', 'Every member is an ordinary payment with settlement_id linking the batch; nonmembers expose null for that field.'],
  ['R11.14', '11', 'Members have a null request_id and the same server-assigned created_at, equal to committed_at.'],
  ['R11.15', '11', 'Constituents follow ordinary activity-feed visibility.'],
  ['R11.16', '11', 'The settlement response contains every member receipt.'],
  ['R11.17', '11', 'Replays return 200 with the original complete response.'],
  ['R11.18', '11', 'This is the fifth idempotent write path in stage 1.'],
  ['R11.19', '11', 'A reset or import preserves settlement operator permissions, original payments, requests, settlement membership and retry responses.'],
];

// The coordinator's recorded interpretations. Checked, always advisory.
export const DECISIONS = [
  ['D4', 'Every payment object carries settlement_id, null unless it is a settlement member.'],
  ['D5', 'Email equality for email_taken is exact byte comparison, so case variants collide at the derived handle and return handle_taken.'],
  ['D6', 'Signup check order: field validation 422, then email_taken 409, then handle_taken 409.'],
  ['D7', 'An email is valid when it has exactly one @, a non-empty local part and a non-empty domain part.'],
  ['D8', 'Timestamps are UTC with a literal +00:00 offset, never Z.'],
  ['D9', 'Ordering is newest-first by created_at, tie-broken by a monotonic creation sequence, newest first.'],
  ['D10', 'Seeded payments and requests get server timestamps at reset in fixture-array order: later in the array is newer.'],
  ['D11', 'Request Content-Type is not enforced; bodies are parsed as JSON regardless.'],
  ['D12', 'An absent or empty request body is the JSON value {}; a present body that is not a JSON object is 400 malformed_request.'],
  ['D13', 'For /requests/{id}/*, a known request with the wrong caller is 403 forbidden, not 404.'],
  ['D14', 'Idempotent write path order: parse body 400, authenticate 401, key present 400, key length 422, key resolution 200/409, then endpoint field validation.'],
  ['D15', 'On /settlements the operator check 403 runs immediately after authentication, before the idempotency key is examined.'],
];

// References this suite deliberately does not check over HTTP, each with the reason.
export const DELIBERATE_GAPS = {
  'R1.6': 'A statement of scope, not a behaviour. The suite tests the HTTP API only, which is what it asserts.',
  'R1.11': 'A statement of scope. Partially covered in substance: the suite checks that money only moves between existing wallets (unknown handle is 404 everywhere). The absence of deposit, top-up, withdrawal, card and bank endpoints is not something an acceptance suite can prove, only the absence of a documented one.',
  'R2.1': 'Repository artefacts (Dockerfile, RUN.md) and the build command. Verified by inspecting the delivered tree and running the documented commands, not over HTTP.',
  'R2.2': 'States that a file is optional. Nothing to check.',
  'R2.3': 'A constraint on the submission form, not on HTTP behaviour.',
  'R2.4': 'How the container is started (-e PORT and a port mapping). The suite is pointed at whatever BASE_URL the launcher produced, so it exercises the result but cannot itself vary PORT. Checked out of band by starting the image twice.',
  'R2.5': 'Run-time network isolation. Checked out of band by starting the container with --network none; the suite is designed to pass in exactly that configuration, which is how it contributes evidence.',
  'R2.7': 'Image contents. Checked out of band by inspecting the built image.',
  'R3.1': 'The bind address and the PORT default are properties of how the process starts. The suite proves the service answers on the URL it was given; 0.0.0.0 and the 8080 default are checked out of band.',
  'R4.4': 'A statement of scope: there is no directory endpoint to test. Recipient identification by handle is covered throughout.',
  'R4.23': 'A statement of scope: there is no administrative balance endpoint to test.',
  'R6.12': 'A statement of scope: there are no such endpoints to test.',
  'R8.36': 'An explicit relaxation, not a requirement. The suite relies on it: it never asserts an order between two items created in the same second, and never asserts pagination stability during concurrent writes.',
  'R10.17': 'An explicit relaxation. The suite never restarts the container and never requires state to survive one.',
  'R10.18': 'An instruction to whoever holds an export, not a service behaviour. Honoured rather than tested: the suite never writes an export to disk and never prints one.',
  'R6.9': 'The header form itself is exercised by every authenticated call in the suite; there is no separate check because a wrong form would fail all of them.',
  'R11.4': 'The body shape is exercised by every settlement check; the malformed-shape rule is checked under R11.7.',
  'R11.18': 'A cross-reference to section 7 rather than a distinct behaviour. The five-path coverage is under R7.1.',
  'R1.10': 'Restated with enforcement detail as R4.1, R4.2 and R4.17, which are checked.',
  'R4.7': 'Restated with its error code as R6.7, which is checked.',
  'R5.3': 'The same rule as R7.5, checked there across all five write paths.',
  'R10.13': 'Checked as part of the export/import preservation check rather than separately.',
  'R5.14': 'The same rule as the limit clause of R8.25, checked there for both list endpoints.',
  'R5.15': 'The same rule as the offset clause of R8.25, checked there for both list endpoints.',
};
